apiVersion: v1 # Define the API version
kind: PersistentVolumeClaim # This resource is a request for storage
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce # Can be used by a single node
  resources:
    requests:
      storage: 1Gi # Request 1 GiB of storage
  storageClassName: standard
