apiVersion: v1
kind: Secret
metadata:
  name: {{ include "story-board.fullname" . }}-backend-creds
  labels:
    app.kubernetes.io/name: {{ include "story-board.fullname" . }}-backend
    app.kubernetes.io/instance: {{ include "story-board.fullname" . }}
type: Opaque
stringData:
  POSTGRES_HOST: {{ include "story-board.fullname" . }}-db
  POSTGRES_PORT: {{ .Values.backend.env.postgresPort | quote }}
  POSTGRES_DB: {{ .Values.backend.env.postgresDb | quote }}
  POSTGRES_USER: {{ .Values.backend.env.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.backend.env.postgresPassword | quote }}
  EXPRESS_PORT: {{ .Values.backend.env.expressPort | quote }}