apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "story-board.fullname" . }}-backend
  labels:
    app.kubernetes.io/name: {{ include "story-board.fullname" . }}-backend
    app.kubernetes.io/instance: {{ include "story-board.fullname" . }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "story-board.fullname" . }}-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "story-board.fullname" . }}-backend
        app.kubernetes.io/instance: {{ include "story-board.fullname" . }}
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "story-board.fullname" . }}-backend-creds
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "story-board.fullname" . }}-backend-creds
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "story-board.fullname" . }}-backend-creds
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "story-board.fullname" . }}-backend-creds
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "story-board.fullname" . }}-backend-creds
                  key: POSTGRES_PASSWORD
            - name: EXPRESS_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "story-board.fullname" . }}-backend-creds
                  key: EXPRESS_PORT
