apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "story-board.fullname" . }}-db
  labels:
    app.kubernetes.io/name: {{ include "story-board.fullname" . }}-db
    app.kubernetes.io/instance: {{ include "story-board.fullname" . }}
spec:
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "story-board.fullname" . }}-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "story-board.fullname" . }}-db
        app.kubernetes.io/instance: {{ include "story-board.fullname" . }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.db.image }}
          ports:
            - containerPort: {{ .Values.db.service.port }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "story-board.fullname" . }}-db-creds
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "story-board.fullname" . }}-db-creds
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "story-board.fullname" . }}-db-creds
                  key: POSTGRES_DB
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: {{ include "story-board.fullname" . }}-db-pvc
        - name: init-scripts
          configMap:
            name: {{ include "story-board.fullname" . }}-db-init-scripts