apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "story-board.fullname" . }}-db-init-scripts
  labels:
    app.kubernetes.io/name: {{ include "helm-chart.fullname" . }}-db
    app.kubernetes.io/instance: {{ include "story-board.fullname" . }}
data:
{{ toYaml .Values.initScripts | nindent 2 }}
