apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "story-board.fullname" . }}-db-pvc
  labels:
    app.kubernetes.io/name: {{ include "story-board.fullname" . }}-db
    app.kubernetes.io/instance: {{ include "story-board.fullname" . }}
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: {{ .Values.db.storage.className | quote }}
  resources:
    requests:
      storage: {{ .Values.db.storage.size | quote }}