apiVersion: v1
kind: Secret
metadata:
  name: {{ include "story-board.fullname" . }}-db-creds
  labels:
    app.kubernetes.io/name: {{ include "story-board.fullname" . }}-db
    app.kubernetes.io/instance: {{ include "story-board.fullname" . }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.db.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.db.password | quote }}
  POSTGRES_DB: {{ .Values.db.database | quote }}