apiVersion: v1
kind: Service
metadata:
  name: {{ include "story-board.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "story-board.fullname" . }}-frontend
    app.kubernetes.io/instance: {{ include "story-board.fullname" . }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "story-board.fullname" . }}-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP