apiVersion: v1
kind: Secret
metadata:
  name: {{ include "story-board.fullname" . }}-frontend-creds
  labels:
    app.kubernetes.io/name: {{ include "story-board.fullname" . }}-frontend
    app.kubernetes.io/instance: {{ include "story-board.fullname" . }}
type: Opaque
stringData:
  OPENAI_KEY: {{ .Values.frontend.env.openaiKey | quote }}
  OPENAI_ACTIVE: {{ .Values.frontend.env.openaiActive | quote }}