# nginx/Dockerfile

# ----------------------------------------------------------------------------------
# STAGE 1: Configure Nginx
# ----------------------------------------------------------------------------------

# Use default nginx image and replace default config with custom
FROM nginx:alpine
COPY default.conf /etc/nginx/conf.d/default.conf