# nginx/Dockerfile

# ----------------------------------------------------------------------------------
# STAGE 1: Configure Nginx
# ----------------------------------------------------------------------------------

# Use default nginx image. Nginx config is done with HELM
FROM nginx:alpine
