apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-creds
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  POSTGRES_HOST: {{ .Values.backend.env.postgresHost | quote }}
  POSTGRES_PORT: {{ .Values.backend.env.postgresPort | quote }}
  POSTGRES_DB: {{ .Values.backend.env.postgresDb | quote }}
  POSTGRES_USER: {{ .Values.backend.env.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.backend.env.postgresPassword | quote }}
  EXPRESS_PORT: {{ .Values.backend.env.expressPort | quote }}