apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-frontend-creds
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  OPENAI_KEY: {{ .Values.frontend.env.openaiKey | quote }}
  OPENAI_ACTIVE: {{ .Values.frontend.env.openaiActive | quote }}