apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db-pvc
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-db
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: {{ .Values.db.storage.className | quote }}
  resources:
    requests:
      storage: {{ .Values.db.storage.size | quote }}