apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-frontend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          env:
            - name: OPENAI_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-frontend-creds
                  key: OPENAI_KEY
            - name: OPENAI_ACTIVE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-frontend-creds
                  key: OPENAI_ACTIVE
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
