name: 🐋 Publish Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push-docker:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU (multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push images
        run: |
          docker build \
            --file client/Dockerfile \
            --build-arg OPENAI_KEY=${{ secrets.OPENAI_KEY }} \
            --build-arg OPENAI_ACTIVE=${{ secrets.OPENAI_ACTIVE }} \
            --tag anirudhktech/story-board-frontend:latest \
            client
          docker push anirudhktech/story-board-frontend:latest

          docker build \
            --file server/Dockerfile \
            --tag anirudhktech/story-board-backend:latest \
            server
          docker push anirudhktech/story-board-backend:latest

          docker build \
            --file nginx/Dockerfile \
            --tag anirudhktech/story-board-nginx:latest \
            nginx
          docker push anirudhktech/story-board-nginx:latest
