name: 🚀 Deploy Terraform Infrastructure

on:
  workflow_run:
    workflows: ["📦 Publish Helm Chart"]
    types:
      - completed

jobs:
  deploy-terraform:
    name: 🚀 Deploy with Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_helm_repo_url: https://anirudhk-tech.github.io/storyboard_ai/
      TF_VAR_helm_release_name: storyboard
      TF_VAR_openai_key: ${{ secrets.OPENAI_KEY }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      TF_VAR_public_dns: ec2-54-145-86-28.compute-1.amazonaws.com

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan & Apply
        run: |
          terraform apply -replace="aws_instance.app" -var="ssh_key_name=Admin" -auto-approve
