name: 🚀 Deploy Terraform Infrastructure

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy-terraform:
    name: 🚀 Deploy with Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_helm_repo_url: https://anirudhk-tech.github.io/storyboard_ai/
      TF_VAR_helm_release_name: storyboard
      TF_VAR_openai_key: ${{ secrets.OPENAI_KEY }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      TF_VAR_public_dns: ec2-54-145-86-28.compute-1.amazonaws.com

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan & Apply
        run: |
          terraform apply -replace="aws_instance.app" -var="ssh_key_name=Admin" -auto-approve

      - name: Get App URL
        id: get-url
        run: |
          APP_HOST=$(terraform output -raw app_public_dns | head -n1)
          echo "app_url=http://${APP_HOST}" >> $GITHUB_OUTPUT

      - name: Show app URL
        run: |
          echo "🎉 App URL is ${{ steps.get-url.outputs.app_url }}"
